

WANDB_NAME:               'basic'
DEVICE:                   'cuda'

# Model

INPUT_CHANNELS:           3

PIC_KERNEL_SIZE:          3
PIC_IN_CHANNELS:          32
PIC_HIDDEN_CHANNELS:      64
PIC_ACTIVATION:           'relu'
PIC_NUMBER:               5
ADD_CONV1x1:              False



# Dataset
DATASET:                  'ImageNet_noise_reduction'
IMAGENET_MEAN:            [90.504, 113.128, 122.296]
IMAGENET_STD:             [73.176, 67.765, 71.750]


NOISE_STD:                1.
IMAGE_SHAPE:              [200, 200]

WIENER_FRAME:             [5, 5]

# Loss
MSE_WEIGHT:               1.0
APPLY_LOSS_EACH_BLOCK:    True



# Optimization
BATCH_SIZE:               4
EPOCHS:                   2
OPTIMZER_NAME:            'Adam'
OPTIMIZER_LR:              0.001
SCHEDULER_NAME:           'cosine'


