
# Model

AGENT_SIZE:               16

PIC_KERNEL_SIZE:          3
PIC_IN_CHANNELS:          32
PIC_HIDDEN_CHANNELS:      64  
PIC_OUT_CHANNELS:         32
PIC_NUMBER_APPLICATION:   5



# Dataset
DATASET:                  'ImageNet_noise_reduction'
IMAGENET_MEAN:            [90.504, 113.128, 122.296]
IMAGENET_STD:             [73.176, 67.765, 71.750]
NOISE_STD:                0.01
IMAGE_SHAPE:              [256, 256]

WIENER_FRAME:             [5, 5]

# Optimization
BATCH_SIZE:               32
EPOCHS:                   10
OPTIMZER_NAME:            'Adam'
OPTIMZER_LR:              0.001
SCHEDULER_NAME:           'cosine'


