

WANDB_NAME:               'deblure'
DEVICE:                   'cuda'

# Model

INPUT_CHANNELS:           3

PIC_KERNEL_SIZE:          3
PIC_IN_CHANNELS:          16
PIC_HIDDEN_CHANNELS:      32
PIC_ACTIVATION:           'relu'
PIC_NUMBER:               5

ADD_CONV1x1:              False
MODIFIER:                 True
GLOBAL_POOL:              'none'  # [avgpool, maxpool, none]
GLOBAL_POOL_PLACE:        'none' # [parallel, serial, none]



# Dataset
DATASET:                 'GoPro_deblure'
DATASET_MEAN:            [111.95842572, 113.79689066, 118.01127043]
DATASET_STD:             [59.39720184, 56.73789445, 56.79359916]


NOISE_STD:                1.
IMAGE_SHAPE:              [128, 128]

WIENER_FRAME:             [5, 5]

# Loss
MSE_WEIGHT:               1.0
APPLY_LOSS_EACH_BLOCK:    True



# Optimization
BATCH_SIZE:               1
EPOCHS:                   3
OPTIMZER_NAME:            'Adam'
OPTIMIZER_LR:              0.001
SCHEDULER_NAME:           'cosine'


